# Generated by Django 4.0.3 on 2022-05-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPlantas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='popi',
            field=models.CharField(default='nombrepopi', help_text='Descripcion de la planta.', max_length=1400),
        ),
    ]
