# Generated by Django 4.0.3 on 2022-05-31 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPlantas', '0002_planta_popi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='popi',
        ),
    ]
