# Generated by Django 4.0.3 on 2022-06-02 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogPlantas', '0003_remove_planta_popi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vivero',
            name='stockPlantas',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='vivero',
            name='stockProductos',
            field=models.CharField(max_length=2000),
        ),
    ]
