# Generated by Django 4.0.3 on 2022-06-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPlantas', '0007_planta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesPosteos'),
        ),
        migrations.AddField(
            model_name='problema',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesProblemas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesProductos'),
        ),
        migrations.AddField(
            model_name='vivero',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesViveros'),
        ),
    ]
